language: python
python:
    - 2.7
sudo: required
cache:
    apt: true
    directories:
        - $HOME/.cache/pip
install:
    - pip install -r vagrant/tournament/requirements.txt
script:
    - pycodestyle --show-source vagrant/tournament/tournament.py
