language: python
python:
    - 2.7
sudo: required
cache:
    apt: true
    directories:
        - $HOME/.cache/pip
services:
    - postgresql
before_script:
    - psql -c '\i vagrant/tournament/tournament.sql' -U postgres
install:
    - pip install -r vagrant/tournament/requirements.txt
script:
    - pycodestyle --show-source vagrant/tournament/tournament.py
    - python vagrant/tournament/tournament_test.py
