language: python
python:
    - 2.7
sudo: required
cache:
    apt: true
    directories:
        - $HOME/.cache/pip
before_install:
    - sudo apt-get -qq update
install:
    - pip install -r requirements.txt
script:
    - pycodestyle --show-source tournamentk.py
